# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/m2m_keygen/all/m2m_keygen.rbi
#
# m2m_keygen-0.1.0

module M2mKeygen
end
class M2mKeygen::Error < StandardError
end
